// Unicode NFC (canonical decomposition, canonical ordering, canonical composition), as applied by the
// HF `NFC` normalizer of the ModernBERT tokenizer. Tables are generated by tools/gen_unicode_nfc.py.

#include "nfc.h"

#include <algorithm>
#include <cstdint>
#include <iterator>
#include <vector>

namespace {

#include "unicode_nfc.inc"

constexpr uint32_t S_BASE = 0xAC00, L_BASE = 0x1100, V_BASE = 0x1161, T_BASE = 0x11A7;
constexpr uint32_t L_COUNT = 19, V_COUNT = 21, T_COUNT = 28, N_COUNT = V_COUNT * T_COUNT, S_COUNT = L_COUNT * N_COUNT;

int ccc(uint32_t cp) {
    if (cp < 0x300) {
        return 0;
    }
    auto it = std::lower_bound(std::begin(NFC_CCC), std::end(NFC_CCC), cp,
                               [](const uint32_t (&e)[2], uint32_t v) { return e[0] < v; });
    return it != std::end(NFC_CCC) && (*it)[0] == cp ? (int) (*it)[1] : 0;
}

void decompose(uint32_t cp, std::vector<uint32_t> & out) {
    if (cp >= S_BASE && cp < S_BASE + S_COUNT) {
        const uint32_t s = cp - S_BASE;
        out.push_back(L_BASE + s / N_COUNT);
        out.push_back(V_BASE + (s % N_COUNT) / T_COUNT);
        if (s % T_COUNT) {
            out.push_back(T_BASE + s % T_COUNT);
        }
        return;
    }
    if (cp >= 0xC0) {
        auto it = std::lower_bound(std::begin(NFC_DECOMP), std::end(NFC_DECOMP), cp,
                                   [](const uint32_t (&e)[3], uint32_t v) { return e[0] < v; });
        if (it != std::end(NFC_DECOMP) && (*it)[0] == cp) {
            out.insert(out.end(), NFC_DECOMP_DATA + (*it)[1], NFC_DECOMP_DATA + (*it)[1] + (*it)[2]);
            return;
        }
    }
    out.push_back(cp);
}

uint32_t compose(uint32_t a, uint32_t b) {
    if (a >= L_BASE && a < L_BASE + L_COUNT && b >= V_BASE && b < V_BASE + V_COUNT) {
        return S_BASE + ((a - L_BASE) * V_COUNT + (b - V_BASE)) * T_COUNT;
    }
    if (a >= S_BASE && a < S_BASE + S_COUNT && (a - S_BASE) % T_COUNT == 0 && b > T_BASE && b < T_BASE + T_COUNT) {
        return a + (b - T_BASE);
    }
    auto it = std::lower_bound(std::begin(NFC_COMP), std::end(NFC_COMP), std::make_pair(a, b),
                               [](const uint32_t (&e)[3], const std::pair<uint32_t, uint32_t> & v) {
                                   return e[0] < v.first || (e[0] == v.first && e[1] < v.second);
                               });
    return it != std::end(NFC_COMP) && (*it)[0] == a && (*it)[1] == b ? (*it)[2] : 0;
}

// UTF-8 decode; invalid bytes are mapped to 0x80000000 | byte and re-emitted unchanged
std::vector<uint32_t> decode_utf8(const std::string & s) {
    std::vector<uint32_t> out;
    out.reserve(s.size());
    for (size_t i = 0; i < s.size();) {
        const unsigned char c = (unsigned char) s[i];
        const int n = c < 0x80 ? 1 : (c >> 5) == 0x6 ? 2 : (c >> 4) == 0xE ? 3 : (c >> 3) == 0x1E ? 4 : 0;
        bool ok = n > 0 && i + n <= s.size();
        uint32_t cp = n == 1 ? c : n == 2 ? (c & 0x1F) : n == 3 ? (c & 0x0F) : (c & 0x07);
        for (int j = 1; ok && j < n; ++j) {
            const unsigned char cc = (unsigned char) s[i + j];
            ok = (cc & 0xC0) == 0x80;
            cp = (cp << 6) | (cc & 0x3F);
        }
        if (!ok) {
            out.push_back(0x80000000u | c);
            i += 1;
        } else {
            out.push_back(cp);
            i += n;
        }
    }
    return out;
}

void encode_utf8(uint32_t cp, std::string & out) {
    if (cp & 0x80000000u) {
        out += (char) (cp & 0xFF);
    } else if (cp < 0x80) {
        out += (char) cp;
    } else if (cp < 0x800) {
        out += (char) (0xC0 | (cp >> 6));
        out += (char) (0x80 | (cp & 0x3F));
    } else if (cp < 0x10000) {
        out += (char) (0xE0 | (cp >> 12));
        out += (char) (0x80 | ((cp >> 6) & 0x3F));
        out += (char) (0x80 | (cp & 0x3F));
    } else {
        out += (char) (0xF0 | (cp >> 18));
        out += (char) (0x80 | ((cp >> 12) & 0x3F));
        out += (char) (0x80 | ((cp >> 6) & 0x3F));
        out += (char) (0x80 | (cp & 0x3F));
    }
}

} // namespace

namespace laya {

std::string nfc(const std::string & text) {
    if (std::all_of(text.begin(), text.end(), [](char c) { return (unsigned char) c < 0x80; })) {
        return text; // ASCII is always NFC
    }
    std::vector<uint32_t> cps;
    for (uint32_t cp : decode_utf8(text)) {
        if (cp & 0x80000000u) {
            cps.push_back(cp);
        } else {
            decompose(cp, cps);
        }
    }
    // canonical ordering: stable sort each run of non-starters by combining class
    for (size_t i = 0; i < cps.size();) {
        if (ccc(cps[i]) == 0) {
            ++i;
            continue;
        }
        size_t j = i;
        while (j < cps.size() && ccc(cps[j]) != 0) {
            ++j;
        }
        std::stable_sort(cps.begin() + i, cps.begin() + j, [](uint32_t a, uint32_t b) { return ccc(a) < ccc(b); });
        i = j;
    }
    // canonical composition (UAX #15 reference algorithm)
    if (!cps.empty()) {
        size_t   starter_pos = 0;
        uint32_t starter     = cps[0];
        int      last_class  = ccc(starter) ? 256 : 0;
        size_t   out         = 1;
        for (size_t i = 1; i < cps.size(); ++i) {
            const uint32_t ch  = cps[i];
            const int      cls = ccc(ch);
            const uint32_t c   = (ch & 0x80000000u) || (starter & 0x80000000u) ? 0 : compose(starter, ch);
            if (c && (last_class < cls || last_class == 0)) {
                cps[starter_pos] = starter = c;
                continue;
            }
            if (cls == 0) {
                starter_pos = out;
                starter     = ch;
            }
            last_class = cls;
            cps[out++] = ch;
        }
        cps.resize(out);
    }
    std::string res;
    res.reserve(text.size());
    for (uint32_t cp : cps) {
        encode_utf8(cp, res);
    }
    return res;
}

} // namespace laya
